name: grocery_store_app
description: Ứng dụng quản lý cửa hàng tạp hoá.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  badges: ^3.1.1
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  sliding_sheet: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"